# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerType', models.CharField(choices=[('\u4e2a\u4eba', '\u4e2a\u4eba'), ('\u4f01\u4e1a', '\u4f01\u4e1a')], default='\u4e2a\u4eba', max_length=5, verbose_name='\u5ba2\u6237\u7c7b\u578b')),
                ('companyName', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('contactName', models.CharField(max_length=10, verbose_name='\u8054\u7cfb\u4eba\u540d\u79f0')),
                ('contactAddr', models.CharField(max_length=30, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('contactTell', models.CharField(max_length=30, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
            ],
            options={
                'ordering': ['companyName'],
            },
        ),
        migrations.CreateModel(
            name='DevInfo',
            fields=[
                ('devID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID')),
                ('isSale', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5356\u51fa')),
                ('isPass', models.BooleanField(default=False, verbose_name='\u662f\u5426\u901a\u8fc7\u68c0\u9a8c')),
            ],
            options={
                'ordering': ['devID'],
            },
        ),
        migrations.CreateModel(
            name='DevType',
            fields=[
                ('devType', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('devPart', models.CharField(max_length=30, verbose_name='\u6240\u5c5e\u90e8\u95e8')),
            ],
            options={
                'ordering': ['devType'],
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('faulltID', models.IntegerField(unique=True, verbose_name='\u6545\u969c\u6e90ID')),
                ('faullt', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u6545\u969c\u6e90')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenanceID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u7ef4\u4feeID')),
                ('inputTime', models.DateTimeField(auto_now=True, verbose_name='\u5f55\u5165\u65f6\u95f4')),
                ('maintenanceTime', models.DateField(verbose_name='\u7ef4\u4fee\u65f6\u95f4')),
                ('statu', models.CharField(max_length=2, verbose_name='\u7ef4\u4fee\u72b6\u6001')),
                ('addr', models.CharField(max_length=40, verbose_name='\u7ef4\u4fee\u5730\u5740')),
                ('maintenancer', models.CharField(max_length=10, verbose_name='\u7ef4\u4fee\u4eba\u5458')),
                ('detail', models.TextField(verbose_name='\u8be6\u7ec6\u4fe1\u606f')),
                ('part', models.TextField(null=True, verbose_name='\u66f4\u6362\u5de5\u4ef6')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.Customer', verbose_name='\u6240\u5c5e\u516c\u53f8')),
                ('devId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevInfo', verbose_name='\u8bbe\u5907ID')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.Fault', verbose_name='\u6545\u969c\u6e90')),
            ],
            options={
                'ordering': ['maintenanceID'],
            },
        ),
        migrations.CreateModel(
            name='pipelineFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ControlPanel', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u63a7\u5236\u677f')),
                ('ControlPanelVersion', models.CharField(max_length=10, verbose_name='\u63a7\u5236\u677f\u7248\u672c\u53f7')),
                ('CarriageAndBracingSheet', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u62d6\u677f\u4e0e\u52a0\u5f3a\u677f')),
                ('Bundle', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u624e\u7ebf')),
                ('caulking', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u6253\u80f6')),
                ('Assembling', models.CharField(max_length=10, verbose_name='\u88c5\u914d\u4eba')),
                ('ProductionDate', models.DateField(auto_now=True, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('devID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevInfo', verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
            ],
            options={
                'ordering': ['devID'],
            },
        ),
        migrations.CreateModel(
            name='pipelineFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterFilterInductor', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u8f93\u5165\u6ee4\u6ce2\u7535\u611f')),
                ('WholeWiring', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], default='\u5b8c\u6210', max_length=6, verbose_name='\u6574\u673a\u63a5\u7ebf')),
                ('AriSwitchBracket', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u7a7a\u6c14\u5f00\u5173\u652f\u67b6')),
                ('AriSwitchModel', models.CharField(choices=[(b'NDM1-63 C50', b'NDM1-63 C50'), (b'NDM1-63 C40', b'NDM1-63 C40'), (b'BM-63 50A', b'BM-63 50A'), (b'BM-63 40A', b'BM-63 40A')], max_length=10, verbose_name='\u7a7a\u6c14\u5f00\u5173\u578b\u53f7')),
                ('AriSwitchMaker', models.CharField(choices=[('\u4e0a\u6d77\u826f\u4fe1\u7535\u5668\u80a1\u4efd\u6709\u9650\u516c\u53f8', '\u4e0a\u6d77\u826f\u4fe1\u7535\u5668\u80a1\u4efd\u6709\u9650\u516c\u53f8'), ('\u53f0\u5b89\u79d1\u6280(\u65e0\u9521)', '\u53f0\u5b89\u79d1\u6280(\u65e0\u9521)')], max_length=20, verbose_name='\u7a7a\u6c14\u5f00\u5173\u5382\u5bb6')),
                ('EnterFilterPlate', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u8f93\u5165\u6ee4\u6ce2\u677f')),
                ('Assembling', models.CharField(max_length=10, verbose_name='\u88c5\u914d\u4eba')),
                ('ProductionDate', models.DateField(auto_now=True, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('devID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevInfo', verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
            ],
            options={
                'ordering': ['devID'],
            },
        ),
        migrations.CreateModel(
            name='pipelineOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuickPlug', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u5feb\u901f\u63d2\u5ea7')),
                ('FBIC', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u5e73\u5e95\u9694\u79bb\u67f1')),
                ('Coil', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u8fc7\u7ebf\u5708')),
                ('DPRP', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u62d6\u677f\u4e0e\u52a0\u5f3a\u677f')),
                ('OutputFilter', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u8f93\u51fa\u6ee4\u6ce2\u677f')),
                ('MainTransformer', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u4e3b\u53d8\u538b\u5668')),
                ('TCRWithPin', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u7535\u6297\u5668\u5b89\u88c5\u4e0e\u5f15\u811a\u63a5\u7ebf')),
                ('ControlTransformer', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u63a7\u5236\u53d8\u538b\u5668')),
                ('Bridge', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u6574\u6d41\u6865')),
                ('EarthStud', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u63a5\u5730\u87ba\u6813')),
                ('AluPlateAndBasePlate', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u94dd\u9694\u677f\u4e0e\u5e95\u677f')),
                ('BridgeHeatSink', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u6574\u6d41\u6865\u6563\u70ed\u5668')),
                ('OutputProtectionRe', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u8f93\u51fa\u4fdd\u62a4\u7535\u963b')),
                ('cap', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u7535\u5bb9(20UF/650v)')),
                ('Assembling', models.CharField(max_length=10, verbose_name='\u88c5\u914d\u4eba')),
                ('ProductionDate', models.DateField(auto_now=True, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('devID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevInfo', verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
            ],
            options={
                'ordering': ['devID'],
            },
        ),
        migrations.CreateModel(
            name='pipelineThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IGBTConnectionAndAB', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='IGBT\u63a5\u7ebf\u4e0eAB\u4fdd\u62a4\u677f')),
                ('FrontAndRearPanels', models.CharField(max_length=6, verbose_name='\u524d,\u540e\u9762\u677f')),
                ('Fan', models.CharField(choices=[(b'200FZY7-D', b'200FZY7-D')], max_length=20, verbose_name='\u98ce\u673a\u578b\u53f7')),
                ('fanmaker', models.CharField(choices=[('\u82cf\u5dde\u7535\u8baf', '\u82cf\u5dde\u7535\u8baf')], max_length=20, verbose_name='\u98ce\u673a\u5382\u5bb6')),
                ('DigitalModel', models.CharField(choices=[(b'PZ50-A13', b'PZ50-A13'), (b'1111-4', b'1111-4')], max_length=20, verbose_name='\u6570\u663e\u8868\u578b\u53f7')),
                ('digitalmaker', models.CharField(choices=[('\u82cf\u5dde\u6a2a\u6cb3', '\u82cf\u5dde\u6a2a\u6cb3'), ('\u4e0a\u6d77\u701a\u663e', '\u4e0a\u6d77\u701a\u663e'), ('\u6210\u90fd\u718a\u8c37', '\u6210\u90fd\u718a\u8c37')], max_length=20, verbose_name='\u6570\u663e\u8868\u5382\u5bb6')),
                ('IGBTPIN', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='IGBT\u63a5\u7ebf')),
                ('TenCoreAirOutlet', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u5341\u82af\u822a\u7a7a\u63d2\u5ea7')),
                ('Assembling', models.CharField(max_length=10, verbose_name='\u88c5\u914d\u4eba')),
                ('ProductionDate', models.DateField(auto_now=True, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('devID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevInfo', verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
            ],
            options={
                'ordering': ['devID'],
            },
        ),
        migrations.CreateModel(
            name='pipelineTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EleCapCom', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u7535\u89e3\u7535\u5bb9\u7ec4\u5408')),
                ('EleCapComModel', models.CharField(choices=[(b'DCMEC 2200uF/400V', b'DCMEC 2200uF/400V'), (b'DCMEC 1000uF/400V', b'DCMEC 1000uF/400V'), (b'50uF/500V', b'50uF/500V')], max_length=20, verbose_name='\u7535\u89e3\u7535\u5bb9\u578b\u53f7')),
                ('EleCapComMaker', models.CharField(choices=[('CDE', 'CDE'), ('\u6c5f\u6d77', '\u6c5f\u6d77'), ('\u4fe1\u8fbe', '\u4fe1\u8fbe'), ('\u65b9\u534e', '\u65b9\u534e'), ('\u5b8f\u5cf0', '\u5b8f\u5cf0')], max_length=10, verbose_name='\u7535\u89e3\u7535\u5bb9\u5382\u5bb6')),
                ('BlockCap', models.CharField(choices=[(b'4uF/1KV', b'4uF/1KV'), (b'5uF/1KV', b'5uF/1KV'), (b'6uF/1KV', b'6uF/1KV'), (b'8uF/1KV', b'8uF/1KV')], max_length=10, verbose_name='\u9694\u76f4\u7535\u5bb9')),
                ('IGBTSINK', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='IGBT\u6563\u70ed\u5668')),
                ('IGBTModel', models.CharField(choices=[(b'FF150R12KS4', b'FF150R12KS4'), (b'FF100R12KS4', b'FF100R12KS4'), (b'SKM100GB128D', b'SKM100GB128D'), (b'SKM75GB128D', b'SKM75GB128D'), (b'GD100HFV12C8S', b'GD100HFV12C8S'), (b'GD75HFV12C8S', b'GD75HFV12C8S')], max_length=20, verbose_name='IGBT\u6a21\u5757\u578b\u53f7')),
                ('IGBTMaker', models.CharField(choices=[('\u897f\u95e8\u5b50', '\u897f\u95e8\u5b50'), ('\u897f\u95e8\u5eb7', '\u897f\u95e8\u5eb7'), ('\u65af\u8fbe', '\u65af\u8fbe')], max_length=10, verbose_name='IGBT\u5382\u5bb6')),
                ('DiodeHeatSink', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u4e8c\u6781\u7ba1\u6a21\u5757\u6563\u70ed\u5668')),
                ('DiodeModel', models.CharField(choices=[(b'MMF200ZB040DK1', b'MMF200ZB040DK1'), (b'DH2F100N4S', b'DH2F100N4S'), (b'MURL20056CT', b'MURL20056CT')], max_length=15, verbose_name='\u4e8c\u6781\u7ba1\u6a21\u5757\u578b\u53f7')),
                ('DiodeMaker', models.CharField(choices=[('\u6c5f\u82cf\u5b8f\u5fae', '\u6c5f\u82cf\u5b8f\u5fae'), ('\u5927\u4f1f', '\u5927\u4f1f'), ('\u5927\u79d1', '\u5927\u79d1')], max_length=10, verbose_name='\u4e8c\u6781\u7ba1\u6a21\u5757\u5382\u5bb6')),
                ('Cap', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u7535\u5bb920uF/650V')),
                ('OutputCopper', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u8f93\u51fa\u94dc\u6392')),
                ('SensorModel', models.CharField(choices=[(b'L03S400D15WM', b'L03S400D15WM'), (b'TBC300BA', b'TBC300BA'), (b'HAS400-S/S950', b'HAS400-S/S950'), (b'TBC300BA', b'TBC300BA')], max_length=20, verbose_name='\u4f20\u611f\u5668\u578b\u53f7')),
                ('SensorMaker', models.CharField(choices=[('\u65e5\u672c\u7530\u6751', '\u65e5\u672c\u7530\u6751'), ('\u83b1\u59c6', '\u83b1\u59c6'), ('\u62d3\u80af', '\u62d3\u80af')], max_length=20, verbose_name='\u4f20\u611f\u5668\u5382\u5bb6')),
                ('TransformerSecSideWiring', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u4e3b\u53d8\u538b\u5668\u526f\u8fb9\u63a5\u7ebf')),
                ('TransformerPriSideWiring', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u4e3b\u53d8\u538b\u5668\u539f\u8fb9\u63a5\u7ebf')),
                ('PhaseInduConnection', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u79fb\u76f8\u7535\u611f\u63a5\u7ebf')),
                ('CommutationInductor', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u6362\u6d41\u7535\u611f\u5b89\u88c5\u4e0e\u63a5\u7ebf')),
                ('ControTransformer', models.CharField(choices=[('\u5b8c\u6210', '\u5b8c\u6210'), ('\u4e0d\u9002\u5408', '\u4e0d\u9002\u5408')], max_length=6, verbose_name='\u63a7\u5236\u53d8\u538b\u5668')),
                ('ControTransformerMaker', models.CharField(choices=[('\u7ef5\u9633\u5929\u610f\u7535\u5b50\u6709\u9650\u516c\u53f8', '\u7ef5\u9633\u5929\u610f\u7535\u5b50\u6709\u9650\u516c\u53f8'), ('\u7ef5\u9633\u5b87\u8679\u7535\u5b50\u6709\u9650\u516c\u53f8', '\u7ef5\u9633\u5b87\u8679\u7535\u5b50\u6709\u9650\u516c\u53f8')], max_length=20, verbose_name='\u63a7\u5236\u53d8\u538b\u5668\u5382\u5bb6')),
                ('Assembling', models.CharField(max_length=10, verbose_name='\u88c5\u914d\u4eba')),
                ('ProductionDate', models.DateField(auto_now=True, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('devID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevInfo', verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
            ],
            options={
                'ordering': ['devID'],
            },
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('saleID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('saleTime', models.TimeField(default=1463816458.856, verbose_name='\u9500\u552e\u65f6\u95f4')),
                ('devID', models.TextField(verbose_name='\u9500\u552e\u8bbe\u5907ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.Customer', verbose_name='\u8d2d\u4e70\u65b9')),
                ('devType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevType', verbose_name='\u8bbe\u5907\u7c7b\u578b')),
            ],
            options={
                'ordering': ['saleID'],
            },
        ),
        migrations.AddField(
            model_name='devinfo',
            name='devType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.DevType', verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
    ]
