# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineone',
            name='id',
        ),
        migrations.AddField(
            model_name='pipelineone',
            name='pipelinOneID',
            field=models.AutoField(default=datetime.datetime(2016, 5, 23, 3, 59, 56, 484000, tzinfo=utc), primary_key=True, serialize=False, verbose_name='\u5de5\u4f4d\u5e8f\u53f7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleinfo',
            name='saleTime',
            field=models.TimeField(default=1463975983.548, verbose_name='\u9500\u552e\u65f6\u95f4'),
        ),
    ]
