# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0003_auto_20160523_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinfo',
            name='saleTime',
            field=models.TimeField(default=1463976285.965, verbose_name='\u9500\u552e\u65f6\u95f4'),
        ),
    ]
