# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0004_auto_20160523_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenanceTime',
        ),
        migrations.AlterField(
            model_name='saleinfo',
            name='saleTime',
            field=models.TimeField(default=1463976488.343, verbose_name='\u9500\u552e\u65f6\u95f4'),
        ),
    ]
