# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0007_auto_20160523_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinfo',
            name='saleTime',
            field=models.DateField(verbose_name='\u9500\u552e\u65f6\u95f4'),
        ),
    ]
